<?xml version="1.0" encoding="utf-8"?><Database Name="KitchenNotesDatabase" Class="DALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=arfsdl2a9g.database.windows.net;Initial Catalog=KitchenNotesDatabase;User ID=andy" SettingsObjectName="KitchenNotesDAL.Properties.Settings" SettingsPropertyName="KitchenNotesDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hub" Member="Hubs">
    <Type Name="Hub">
      <Column Name="HubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HubName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="Hub_UserHub" Member="UserHubs" ThisKey="HubId" OtherKey="HubId" Type="UserHub" />
    </Type>
  </Table>
  <Table Name="dbo.Notes" Member="Notes">
    <Type Name="Note">
      <Column Name="NoteId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Member="Note1" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserHubId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="UserHub_Note" Member="UserHub" ThisKey="UserHubId" OtherKey="UserHubId" Type="UserHub" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Forename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="RememberMe" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_UserHub" Member="UserHubs" ThisKey="UserId" OtherKey="UserId" Type="UserHub" />
    </Type>
  </Table>
  <Table Name="dbo.UserHub" Member="UserHubs">
    <Type Name="UserHub">
      <Column Name="UserHubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="HubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Association Name="UserHub_Note" Member="Notes" ThisKey="UserHubId" OtherKey="UserHubId" Type="Note" />
      <Association Name="Hub_UserHub" Member="Hub" ThisKey="HubId" OtherKey="HubId" Type="Hub" IsForeignKey="true" />
      <Association Name="User_UserHub" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>