<?xml version="1.0" encoding="utf-8"?><Database Name="KitchNotesDatabase" Class="DALDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sqlserverkn.westeurope.cloudapp.azure.com;Initial Catalog=KitchNotesDatabase;User ID=AdminAndy;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="KitchenNotesDAL.Properties.Settings" SettingsPropertyName="KitchNotesDatabaseConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hub" Member="Hubs">
    <Type Name="Hub">
      <Column Name="HubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HubName" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="HubAddress" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="HubLocation" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="Hub_UserHub" Member="UserHubs" ThisKey="HubId" OtherKey="HubId" Type="UserHub" />
    </Type>
  </Table>
  <Table Name="dbo.HubEvents" Member="HubEvents">
    <Type Name="HubEvent">
      <Column Name="HubEventId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserHubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NChar(300)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Importance" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserHub_HubEvent" Member="UserHub" ThisKey="UserHubId" OtherKey="UserHubId" Type="UserHub" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notes" Member="Notes">
    <Type Name="Notes">
      <Column Name="NoteId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserHubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DateEdited" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateHidden" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="UserHub_Note" Member="UserHub" ThisKey="UserHubId" OtherKey="UserHubId" Type="UserHub" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Tasks">
      <Column Name="TaskId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TaskDetail" Type="System.String" DbType="NChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AssignedTo" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="UserHubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Completed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Hidden" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DatePosted" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="UserHub_Task" Member="UserHub" ThisKey="UserHubId" OtherKey="UserHubId" Type="UserHub" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Forename" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentHub" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_UserHub" Member="UserHubs" ThisKey="UserId" OtherKey="UserId" Type="UserHub" />
    </Type>
  </Table>
  <Table Name="dbo.UserHub" Member="UserHubs">
    <Type Name="UserHub">
      <Column Name="UserHubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="HubId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="HubAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserHub_HubEvent" Member="HubEvents" ThisKey="UserHubId" OtherKey="UserHubId" Type="HubEvent" />
      <Association Name="UserHub_Note" Member="Notes" ThisKey="UserHubId" OtherKey="UserHubId" Type="Notes" />
      <Association Name="UserHub_Task" Member="Tasks" ThisKey="UserHubId" OtherKey="UserHubId" Type="Tasks" />
      <Association Name="Hub_UserHub" Member="Hub" ThisKey="HubId" OtherKey="HubId" Type="Hub" IsForeignKey="true" />
      <Association Name="User_UserHub" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>