//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitchenNotesDAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=arfsdl2a9g.database.windows.net;Initial Catalog=KitchenNotesDatabase;" +
            "User ID=andy;Password=Graham@2015")]
        public string KitchenNotesDatabaseConnectionString {
            get {
                return ((string)(this["KitchenNotesDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-5OK3L3RNJQ8;Initial Catalog=KitchNotesDB;Integrated Security=True" +
            "")]
        public string KitchNotesDBConnectionString {
            get {
                return ((string)(this["KitchNotesDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDY-PC;Initial Catalog=KitchNotesDatabase;Integrated Security=True")]
        public string KitchNotesDatabaseConnectionString {
            get {
                return ((string)(this["KitchNotesDatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqlserverkn.westeurope.cloudapp.azure.com;Initial Catalog=KitchNotesD" +
            "atabase;User ID=AdminAndy;Password=Graham@2015")]
        public string KitchNotesDatabaseConnectionString1 {
            get {
                return ((string)(this["KitchNotesDatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sqlserverkn.westeurope.cloudapp.azure.com;Initial Catalog=KitchNotesD" +
            "atabase;User ID=AdminAndy;Password=Graham@2015;Encrypt=False;TrustServerCertific" +
            "ate=True")]
        public string KitchNotesDatabaseConnectionString2 {
            get {
                return ((string)(this["KitchNotesDatabaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ANDY-PC;Initial Catalog=KitchNotesDatabase;Integrated Security=True;C" +
            "onnect Timeout=60;Encrypt=False;TrustServerCertificate=True")]
        public string KitchNotesDatabaseConnectionString3 {
            get {
                return ((string)(this["KitchNotesDatabaseConnectionString3"]));
            }
        }
    }
}
