//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalAppService
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubEvent
    {
        public System.Guid HubEventId { get; set; }
        public System.Guid UserHubId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Importance { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual UserHub UserHub { get; set; }
    }
}
