//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversalAppService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public System.Guid NoteId { get; set; }
        public string Note { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.Guid UserHubId { get; set; }
        public Nullable<System.DateTime> DateEdited { get; set; }
        public Nullable<System.DateTime> DateHidden { get; set; }
    
        public virtual UserHub UserHub { get; set; }
    }
}
